# Generated by Django 2.2.4 on 2019-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_auto_20190814_0858'),
        ('user', '0004_auto_20190814_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_job',
            field=models.ManyToManyField(related_name='save_set', to='Job.Post'),
        ),
    ]
