# Generated by Django 2.2.4 on 2019-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20190814_0735'),
        ('user', '0005_profile_save_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_project',
            field=models.ManyToManyField(related_name='save_set', to='Project.Project'),
        ),
    ]
