# Generated by Django 2.2.4 on 2019-08-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190814_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
