# Generated by Django 2.2.4 on 2019-08-16 06:29
from django.utils import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
