# Generated by Django 2.2.4 on 2019-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20190816_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_is',
            field=models.BooleanField(default=False),
        ),
    ]
