# Generated by Django 2.2.4 on 2019-08-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_comment_reply_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
