# Generated by Django 2.2.4 on 2019-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_auto_20190814_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
