# Generated by Django 2.2.4 on 2019-08-19 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0007_auto_20190819_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(null=True, related_name='save_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
